---
name: bind9

instance_groups:
  - name: master
    azs:  [z1]

    stemcell: default
    vm_type: default
    networks:
      - name: default

    instances: 1
    jobs:
      - name:    master
        release: bind9
        properties:
          network: 10.0.0.0/8
          zones:
            foo.bl: |+
              $TTL 1h
              $ORIGIN foo.bl.
              @ IN SOA foo.bl. hostmaster.foo.bl. (
                         2015082505  ; serial
                         15m         ; slaves should check back with us every 15min
                         20          ; slaves should retry (on failure) after 20sec
                         4h          ; slaves stop being authoritative after 4hr without updates
                         1h          ; other NSes should cache our results for 1h
                       )
                     IN NS ns1.foo.bl.
                     IN NS ns2.foo.bl.
                     IN A  10.0.0.42 ; bar
              ns1    IN A  10.0.0.11
              ns2    IN A  10.0.0.12
              bar    IN A  10.0.0.42
            10.in-addr.arpa: |+
              $TTL 1h
              $ORIGIN 10.in-addr.arpa.
              @ IN SOA foo.bl. hostmaster.foo.bl. (
                         2015082504  ; serial
                         15m         ; slaves should check back with us every 15min
                         20          ; slaves should retry (on failure) after 20sec
                         4h          ; slaves stop being authoritative after 4hr without updates
                         1h          ; other NSes should cache our results for 1h
                       )
                      IN NS  ns1.foo.bl.
                      IN NS  ns2.foo.bl.
              11.0.0  IN PTR ns1.foo.bl.
              12.0.0  IN PTR ns2.foo.bl.
              42.0.0  IN PTR bar.foo.bl.


  - name: slave
    azs:  [z2]

    stemcell: default
    vm_type: default
    networks:
      - name: default

    instances: 2
    jobs:
    - { release: bind9, name: slave }


stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-120000

releases:
- name:    bind9
  version: 1.1.4
  url:     https://github.com/cloudfoundry-community/bind9-boshrelease/releases/download/v1.1.4/bind9-1.1.4.tgz
  sha1:    cfd9fd042fbe03a7cda7c6f68b443a3bcf172092
