---
meta:
  name:    bind9
  release: BIND9
  target:  pipes
  url:     https://pipes.starkandwayne.com

  initial_version: 0.2.0

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot

  bosh-lite:
    target:   https://10.128.4.73:25555
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  cloudfoundry-community
    repo:   bind9-boshrelease
    branch: master
    private_key:  ((starkandwayne-bot-github.private-key))
    access_token: ((starkandwayne-bot-github.access-token))

  shout:
    url:      http://10.128.4.65:7109
    username: ((shout.username))
    password: ((shout.password))
